### ISSUE TITLE
[Bug] Flattening Bulk Workflow

### ISSUE THREAD

**Issue by cmarshak** [OPERA-Cal-Val/calval-RTC#14]
Using Brazil site, I came across this issue:

```
Executing:  56%|█████▌    | 20/36 [00:02<00:02,  6.89cell/s]
Traceback (most recent call last):
  File "/Users/cmarshak/bekaert-team/calval-RTC/bulk_validation_scripts/bulk_papermill_OPERA_RTC_flattening.py", line 275, in <module>
    main()
  File "/Users/cmarshak/bekaert-team/calval-RTC/bulk_validation_scripts/bulk_papermill_OPERA_RTC_flattening.py", line 271, in main
    flatten(input_data_dir)
  File "/Users/cmarshak/bekaert-team/calval-RTC/bulk_validation_scripts/bulk_papermill_OPERA_RTC_flattening.py", line 233, in flatten
    pm.execute_notebook(
  File "/Users/cmarshak/mambaforge/envs/opera_calval_rtc/lib/python3.11/site-packages/papermill/execute.py", line 128, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/Users/cmarshak/mambaforge/envs/opera_calval_rtc/lib/python3.11/site-packages/papermill/execute.py", line 232, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError:
---------------------------------------------------------------------------
Exception encountered at "In [11]":
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[11], line 15
     13     land_cover = list(data_dir.glob('merged_*.tif'))[0]
     14 else:
---> 15     land_cover = land_cover[0]

IndexError: list index out of range

```

**Comment by cmarshak** [comment]
[output_OPERA_L2-RTC_S1A_IW_SLC__1SDV_20210528T092214_20210528T092242_038086_047EB2_5BE8_30_v1.0_prep_flattening_part_1.pdf](https://github.com/OPERA-Cal-Val/calval-RTC/files/13418236/output_OPERA_L2-RTC_S1A_IW_SLC__1SDV_20210528T092214_20210528T092242_038086_047EB2_5BE8_30_v1.0_prep_flattening_part_1.pdf)

Above is the output jupyter notebook.

**Comment by cmarshak** [comment]
Looks like wget needs to be installed in the conda environment.

**Comment by Alex-Lewandowski** [comment]
Thanks, @cmarshak. I added wget to both yamls in this PR (https://github.com/OPERA-Cal-Val/calval-RTC/pull/15), and requested you as a reviewer.
